baseURL = 'https://stemn.no/'
languageCode = 'nb-no'
title = 'STEM Norway'


theme="r-hugo-theme"
enableRobotsTXT = true
disableKinds = ["taxonomy", "term", "RSS"]
enableGitInfo = true # Use Git/file times for <lastmod> in pages and sitemap

[markup]
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true # Allow raw HTML, important for JSON-LD etc.

[minify]
minifyOutput = true

