baseURL = 'https://stemn.no/'
languageCode = 'nb-no'
title = 'STEM Norway'
theme = 'ananke'
disqusShortname = 'stemnorway'

[params]
  description = 'Vi jobber for å styrke STEM-feltene i Norge gjennom kampanjer, møter, kurs og aktivisme.'
  favicon = "images/favicon.ico"
  logo = "images/logo.svg"
  
  # Social media
  twitter = "stemnorway"
  github = "stemnorway"
  linkedin = "company/stemnorway"
